create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique check (char_length(trim(username)) >= 2),
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  content_type text not null check (content_type in ('project', 'tutorial')),
  content_slug text not null,
  parent_id bigint references public.comments(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade default auth.uid(),
  username text not null,
  message text not null check (char_length(trim(message)) > 0),
  created_at timestamptz not null default now()
);

create index if not exists comments_lookup_idx
  on public.comments(content_type, content_slug, created_at desc);

alter table public.profiles enable row level security;
alter table public.comments enable row level security;

drop policy if exists "profiles are public read" on public.profiles;
create policy "profiles are public read"
  on public.profiles
  for select
  to public
  using (true);

drop policy if exists "users insert own profile" on public.profiles;
create policy "users insert own profile"
  on public.profiles
  for insert
  to authenticated
  with check (id = auth.uid());

drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile"
  on public.profiles
  for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

drop policy if exists "comments are public read" on public.comments;
create policy "comments are public read"
  on public.comments
  for select
  to public
  using (true);

drop policy if exists "authenticated users can write comments" on public.comments;
create policy "authenticated users can write comments"
  on public.comments
  for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and username = (
      select p.username from public.profiles p where p.id = auth.uid()
    )
  );
